### ISSUE TITLE
Game freezes on month 1 transition

### ISSUE THREAD

**Issue by casillasenrique** [civic-data-design-lab/ecuador-integration#27]
Game freezes after choosing occupation and you go into month 1. Clicking "continue" does nothing.

### Reproduction
Unknown, perhaps a refresh after the migrant/job selection page causes some state to update.

### Logs
```
Uncaught TypeError: Cannot read properties of null (reading 'incomeStore')
    at Array.<anonymous> (game-page.svelte.c04f6edc.js:155:36380)
    at Object.f [as set] (index.77b280a4.js:1:300)
    at Object.c (index.7d97419d.js:1:2351)
    at index.38bf2a04.js:1:1546
    at Set.forEach (<anonymous>)
    at dt (index.38bf2a04.js:1:1532)
```

**Comment by casillasenrique** [comment]
Reproduction found: Adjust the sliders after the job select page
